networks:
  myapp-network:

services:
  myapp:
    networks:
      - myapp-network
    image: myapp
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    command: ["python", "-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "-m",  "gunicorn", "--workers=5", "--threads=1", "-b 0.0.0.0:8000", "index:app"]
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      FLASK_APP: index.py
